### GET All Product
GET http://localhost:3000/api/produk
content-type: application/json

### Insert New Product
POST http://localhost:3000/api/produk
content-type: application/json

{
    "name": "Keyboard",
    "price": "150000",
    "description" : "Hyper sensitive keyboard",
    "stock" : 1
}

### Detail Product
GET http://localhost:3000/api/produk/68f7832b2cf562fae22a2b08

### Update Product
PUT http://localhost:3000/api/produk/68f7832b2cf562fae22a2b08
content-type: application/json

{
    "price": "600000",
    "stock" : 5
}

### Delete Product
DELETE http://localhost:3000/api/produk/68f7832b2cf562fae22a2b08